name: Publish in DockerHub

on:  
  workflow_dispatch:
  push:

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Run tests
        run: mvn test
      - name: Generate tag
        run: echo ::set-output name=tag::$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)
        id: project
      - name: Generate tag
        run: echo ::set-output name=value::$(date +'%d-%m-%Y.%H%M%S')
        id: timestamp
      - name: Generate Docker image
        run: mvn spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=${{ secrets.DOCKERHUB_USERNAME }}/items:${{ steps.project.outputs.tag }}-${{ steps.timestamp.outputs.value }}
      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}" 
      - name: Gnerate repo
        run: docker tag local-image:${{ steps.project.outputs.tag }}-${{ steps.timestamp.outputs.value }} new-repo:${{ secrets.DOCKERHUB_USERNAME }}/items:${{ steps.project.outputs.tag }}-${{ steps.timestamp.outputs.value }}
      - name: Push image to DockerHub
        run: docker push new-repo:${{ secrets.DOCKERHUB_USERNAME }}/items:${{ steps.project.outputs.tag }}-${{ steps.timestamp.outputs.value }}
